"""add activo field to tipo_examen

Revision ID: 1bad4a6d551f
Revises: 776012f5af9f
Create Date: 2026-07-21 14:11:19.654454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad4a6d551f'
down_revision: Union[str, None] = '776012f5af9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_examen', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_examen', 'activo')
    # ### end Alembic commands ###
