"""add paciente ciudad/regimen and usuario firma/registro fields

Revision ID: 3f918cef5b86
Revises: 1bad4a6d551f
Create Date: 2026-07-31 21:54:46.545411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f918cef5b86'
down_revision: Union[str, None] = '1bad4a6d551f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('ciudad', sa.String(), nullable=True))
    op.add_column('paciente', sa.Column('regimen_afiliacion', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('registro_profesional', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('firma_imagen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'firma_imagen')
    op.drop_column('usuario', 'registro_profesional')
    op.drop_column('paciente', 'regimen_afiliacion')
    op.drop_column('paciente', 'ciudad')
    # ### end Alembic commands ###
