"""initial schema

Revision ID: 7c811e529446
Revises: 
Create Date: 2026-07-12 14:09:45.500141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c811e529446'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encuesta',
    sa.Column('id_encuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_encuesta')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identificacion', sa.String(), nullable=False),
    sa.Column('tipo_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('eps', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('hijos', sa.Integer(), nullable=True),
    sa.Column('estudios', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_examen',
    sa.Column('id_tipo_examen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('tipo_muestra', sa.String(), nullable=True),
    sa.Column('tecnica_utilizada', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_examen')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identificacion', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('cita',
    sa.Column('id_cita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('localidad', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('AGENDADA', 'EN_ESPERA', 'EN_ATENCION', 'FINALIZADA', name='estadocita'), nullable=False),
    sa.Column('consentimiento_firmado', sa.Boolean(), nullable=False),
    sa.Column('ruta_consentimiento', sa.String(), nullable=True),
    sa.Column('firma_digital', sa.LargeBinary(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_table('pregunta',
    sa.Column('id_pregunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('tipo_respuesta', sa.String(), nullable=False),
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_encuesta'], ['encuesta.id_encuesta'], ),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('examen_realizado',
    sa.Column('id_examen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('precio_cobrado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', name='estadoexamen'), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('id_tipo_examen', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cita'], ['cita.id_cita'], ),
    sa.ForeignKeyConstraint(['id_tipo_examen'], ['tipo_examen.id_tipo_examen'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_examen')
    )
    op.create_table('respuesta_encuesta',
    sa.Column('id_respuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cita'], ['cita.id_cita'], ),
    sa.ForeignKeyConstraint(['id_pregunta'], ['pregunta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_respuesta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta_encuesta')
    op.drop_table('examen_realizado')
    op.drop_table('usuario_rol')
    op.drop_table('pregunta')
    op.drop_table('cita')
    op.drop_table('usuario')
    op.drop_table('tipo_examen')
    op.drop_table('rol')
    op.drop_table('paciente')
    op.drop_table('encuesta')
    # ### end Alembic commands ###
